const { Character } = require('../models');

const characterData = [
    {
      name: 'Bulbasaur',
      Number: 1,
      type: 'Grass, Poison',
      generation: '1',
      filename: '001Bulbasaur.png',
      catchrate: 11.9,
    },
    {
      name: 'Ivysaur',
      Number: 2,
      type: 'Grass, Poison',
      generation: '1',
      filename: '002Ivysaur.png',
      catchrate: 11.9,
    },
    {
      name: 'Venusaur',
      Number: 3,
      type: 'Grass, Poison',
      generation: '1',
      catchrate: 11.9,
    },
    {
      name: 'Charmander ',
      Number: 4,
      type: 'Fire',
      generation: '1',
      catchrate: 11.9,
    },
    {
      name: 'Charmeleon',
      Number: 5,
      type: 'Fire',
      generation: '1',
      catchrate: 11.9,
    },
    {
      name: 'Charizard',
      Number: 6,
      type: 'Fire',
      generation: '1',
      catchrate: 11.9,
    },
    {
      name: 'Squirtle ',
      Number: 7,
      type: 'Water',
      generation: '1',
      catchrate: 11.9,
    },
    {
      name: 'Wartortle',
      Number: 8,
      type: 'Water',
      generation: '1',
      catchrate: 11.9,
    },
    {
      name: 'Blastoise',
      Number: 9,
      type: 'Water',
      generation: '1',
      catchrate: 11.9,
    },
    {
      name: 'Caterpie',
      Number: 10,
      type: 'Bug',
      generation: '1',
      catchrate: 43.9,
    },
    {
      name: 'Metapod',
      Number: 11,
      type: 'Bug',
      generation: '1',
      catchrate: 24.9,
    },
    {
      name: 'Butterfree',
      Number: 12,
      type: 'Bug, Flying',
      generation: '1',
      catchrate: 11.9,
    },
    {
      name: 'Weedle',
      Number: 13,
      type: 'Bug, Poison',
      generation: '1',
      catchrate: 43.9,
    },
    {
      name: 'Kakuna',
      Number: 14,
      type: 'Bug, Poison',
      generation: '1',
      catchrate: 24.9,
    },
    {
      name: 'Beedrill',
      Number: 15,
      type: 'Bug, Poison',
      generation: '1',
      catchrate: 11.9,
    },
    {
      name: 'Pidgey',
      Number: 16,
      type: 'Normal, Flying',
      generation: '1',
      catchrate: 43.9,
    },
    {
      name: 'Pidgey',
      Number: 17,
      type: 'Normal, Flying',
      generation: '1',
      catchrate: 24.9,
    },
    {
      name: 'Pidgeot',
      Number: 18,
      type: 'Normal, Flying',
      generation: '1',
      catchrate: 11.9,
    },
    {
      name: 'Rattata',
      Number: 19,
      type: 'Normal',
      generation: '1',
      catchrate: 43.9,
    },
    {
      name: 'Raticate',
      Number: 20,
      type: 'Normal',
      generation: '1',
      catchrate: 26,
    },
    {
      name: 'Spearow',
      Number: 21,
      type: 'Normal, Flying',
      generation: '1',
      catchrate: 43.9,
    },
    {
      name: 'Fearow',
      Number: 22,
      type: 'Normal, Flying',
      generation: '1',
      catchrate: 20.1,
    },
    {
      name: 'Ekans',
      Number: 23,
      type: 'Poison',
      generation: '1',
      catchrate: 43.9,
    },
    {
      name: 'Arbok',
      Number: 24,
      type: 'Poison',
      generation: '1',
      catchrate: 20.1,
    },
    {
      name: 'Pikachu',
      Number: 25,
      type: 'Electric',
      generation: '1',
      catchrate: 35.2,
    },
    {
      name: 'Raichu',
      Number: 26,
      type: 'Electric',
      generation: '1',
      catchrate: 17.5,
    },
    {
      name: 'Sandshrew',
      Number: 27,
      type: 'Ground',
      generation: '1',
      catchrate: 17.5,
    },
    {
      name: 'Sandslash',
      Number: 28,
      type: 'Ground',
      generation: '1',
      catchrate: 17.5,
    },
    {
      name: 'NidoranMale',
      Number: 29,
      type: 'Poison',
      generation: '1',
      catchrate: 17.5,
    },
    {
      name: 'Nidorina',
      Number: 30,
      type: 'Poison',
      generation: '1',
      catchrate: 17.5,
    },
    {
      name: 'Nidoqueen',
      Number: 31,
      type: 'Poison, Ground',
      generation: '1',
      catchrate: 17.5,
    },
    {
      name: 'NidoranFemale',
      Number: 32,
      type: 'Poison',
      generation: '1',
      catchrate: 17.5,
    },
    {
      name: 'Nidorino',
      Number: 33,
      type: 'Poison',
      generation: '1',
      catchrate: 17.5,
    },
    {
      name: 'Nidoking',
      Number: 34,
      type: 'Poison, Ground',
      generation: '1',
      catchrate: 17.5,
    },
    {
      name: 'Clefairy',
      Number: 35,
      type: 'Fairy',
      generation: '1',
      catchrate: 17.5,
    },
    {
      name: 'Clefable',
      Number: 36,
      type: 'Fairy',
      generation: '1',
      catchrate: 17.5,
    }, 
    {
      name: 'Vulprix',
      Number: 37,
      type: 'Fire',
      generation: '1',
      catchrate: 17.5,
    }, 
     {
      name: 'Ninetables',
      Number: 38,
      type: 'Fire',
      generation: '1',
      catchrate: 17.5,
    },  
    {
      name: 'Jigglypuff',
      Number: 39,
      type: 'Normal, Fairy',
      generation: '1',
      catchrate: 17.5,
    },  
    {
      name: 'Wigglytuff',
      Number: 40,
      type: 'Normal, Fairy',
      generation: '1',
      catchrate: 17.5,
    }, 
    {
      name: 'Zubat',
      Number: 41,
      type: 'Poison, Flying',
      generation: '1',
      catchrate: 17.5,
    },  
    {
      name: 'Golbat',
      Number: 42,
      type: 'Poison, Flying',
      generation: '1',
      catchrate: 17.5,
    },  
    {
      name: 'Oddish',
      Number: 43,
      type: 'Grass, Poison',
      generation: '1',
      catchrate: 17.5,
    },  
    {
      name: 'Gloom',
      Number: 44,
      type: 'Grass, Poison',
      generation: '1',
      catchrate: 17.5,
    },  
    {
      name: 'Vileplume',
      Number: 45,
      type: 'Grass, Poison',
      generation: '1',
      catchrate: 17.5,
    }, 
    {
      name: 'Paras',
      Number: 46,
      type: 'Bug, Grass',
      generation: '1',
      catchrate: 17.5,
    },
    {
      name: 'Parasect',
      Number: 47,
      type: 'Bug, Grass',
      generation: '1',
      catchrate: 17.5,
    },
    {
      name: 'Venonat',
      Number: 48,
      type: 'Bug, Poison',
      generation: '1',
      catchrate: 17.5,
    },
    {
      name: 'Venomoth',
      Number: 49,
      type: 'Bug, Poison',
      generation: '1',
      catchrate: 17.5,
    },
    {
      name: 'Diglett',
      Number: 50,
      type: 'Ground',
      generation: '1',
      catchrate: 17.5,
    },
    {
      name: 'Dugtrio',
      Number: 51,
      type: 'Ground',
      generation: '1',
      catchrate: 17.5,
    },
    {
      name: 'Meowth',
      Number: 52,
      type: 'Normal',
      generation: '1',
      catchrate: 17.5,
    },
    {
      name: 'Persian',
      Number: 53,
      type: 'Normal',
      generation: '1',
      catchrate: 17.5,
    },
    {
      name: 'Psyduck',
      Number: 54,
      type: 'Water',
      generation: '1',
      catchrate: 17.5,
    },
    {
      name: 'Golduck',
      Number: 55,
      type: 'Water',
      generation: '1',
      catchrate: 17.5,
    },
    {
      name: 'Mankey',
      Number: 56,
      type: 'Fighting',
      generation: '1',
      catchrate: 17.5,
    },
    {
      name: 'Primeape',
      Number: 57,
      type: 'Fighting',
      generation: '1',
      catchrate: 17.5,
    },
    {
      name: 'Growlithe',
      Number: 58,
      type: 'Fire',
      generation: '1',
      catchrate: 17.5,
    },
    {
      name: 'Arcanine',
      Number: 59,
      type: 'Fire',
      generation: '1',
      catchrate: 17.5,
    },
    {
      name: 'Poliwag',
      Number: 60,
      type: 'Water',
      generation: '1',
      catchrate: 17.5,
    },
    {
      name: 'Poliwhirl',
      Number: 61,
      type: 'Water',
      generation: '1',
      catchrate: 17.5,
    },
    {
      name: 'Poliwrath',
      Number: 62,
      type: 'Water, Fighting',
      generation: '1',
      catchrate: 17.5,
    },
    {
      name: 'Abra',
      Number: 63,
      type: 'Psychic',
      generation: '1',
      catchrate: 17.5,
    },
    {
      name: 'Kadabra',
      Number: 64,
      type: 'Psychic',
      generation: '1',
      catchrate: 17.5,
    },
    {
      name: 'Alakazam',
      Number: 65,
      type: 'Psychic',
      generation: '1',
      catchrate: 17.5,
    },
    {
      name: 'Machop',
      Number: 66,
      type: 'Fighting',
      generation: '1',
      catchrate: 17.5,
    },
    {
      name: 'Machoke',
      Number: 67,
      type: 'Fighting',
      generation: '1',
      catchrate: 17.5,
    },
    {
      name: 'Machamp',
      Number: 68,
      type: 'Fighting',
      generation: '1',
      catchrate: 17.5,
    },
    {
      name: 'Bellsprout',
      Number: 69,
      type: 'Grass, Poison',
      generation: '1',
      catchrate: 17.5,
    },
    {
      name: 'Weepinbell',
      Number: 70,
      type: 'Grass, Poison',
      generation: '1',
      catchrate: 17.5,
    },
    {
      name: 'Victreebel',
      Number: 71,
      type: 'Grass, Poison',
      generation: '1',
      catchrate: 17.5,
    },
    {
      name: 'Tentacool',
      Number: 72,
      type: 'Water, Poison',
      generation: '1',
      catchrate: 17.5,
    },
    {
      name: 'Tentacruel',
      Number: 73,
      type: 'Water, Poison',
      generation: '1',
      catchrate: 17.5,
    },
    {
      name: 'Geodude',
      Number: 74,
      type: 'Rock, Ground',
      generation: '1',
      catchrate: 17.5,
    },
    {
      name: 'Graveler',
      Number: 75,
      type: 'Rock, Ground',
      generation: '1',
      catchrate: 17.5,
    },
    {
      name: 'Golem',
      Number: 76,
      type: 'Rock, Ground',
      generation: '1',
      catchrate: 17.5,
    },
    {
      name: 'Ponyta',
      Number: 77,
      type: 'Fire',
      generation: '1',
      catchrate: 17.5,
    },
    {
      name: 'Rapidash',
      Number: 78,
      type: 'Fire',
      generation: '1',
      catchrate: 17.5,
    },
    {
      name: 'Slowpoke',
      Number: 79,
      type: 'Water, Psychic',
      generation: '1',
      catchrate: 17.5,
    },
    {
      name: 'Slowbro',
      Number: 80,
      type: 'Water, Psychic',
      generation: '1',
      catchrate: 17.5,
    },
    {
      name: 'Magnemite',
      Number: 81,
      type: 'Electric, Steel',
      generation: '1',
      catchrate: 17.5,
    },
    {
      name: 'Magneton',
      Number: 82,
      type: 'Electric, Steel',
      generation: '1',
      catchrate: 17.5,
    },
    {
      name: 'Farfetchd',
      Number: 83,
      type: 'Normal, Flying',
      generation: '1',
      catchrate: 17.5,
    },
    {
      name: 'Doduo',
      Number: 84,
      type: 'Normal, Flying',
      generation: '1',
      catchrate: 17.5,
    },
    {
      name: 'Dodrio',
      Number: 85,
      type: 'Normal, Flying',
      generation: '1',
      catchrate: 17.5,
    },
    {
      name: 'Seel',
      Number: 86,
      type: 'Water',
      generation: '1',
      catchrate: 17.5,
    },
    {
      name: 'Dewgong',
      Number: 87,
      type: 'Water, Ice',
      generation: '1',
      catchrate: 17.5,
    },
    {
      name: 'Grimer',
      Number: 88,
      type: 'Poison',
      generation: '1',
      catchrate: 17.5,
    },
    {
      name: 'Muk',
      Number: 89,
      type: 'Poison',
      generation: '1',
      catchrate: 17.5,
    },
    {
      name: 'Shellder',
      Number: 90,
      type: 'Water',
      generation: '1',
      catchrate: 17.5,
    },
    {
      name: 'Cloyster',
      Number: 91,
      type: 'Water, Ice',
      generation: '1',
      catchrate: 17.5,
    },
    {
      name: 'Gastly',
      Number: 92,
      type: 'Ghost, Poison',
      generation: '1',
      catchrate: 17.5,
    },
    {
      name: 'Haunter',
      Number: 93,
      type: 'Ghost, Poison',
      generation: '1',
      catchrate: 17.5,
    },
    {
      name: 'Gengar',
      Number: 94,
      type: 'Ghost, Poison',
      generation: '1',
      catchrate: 17.5,
    },
    {
      name: 'Onix',
      Number: 95,
      type: 'Rock, Ground',
      generation: '1',
      catchrate: 17.5,
    },
    {
      name: 'Drowzee',
      Number: 96,
      type: 'Psychic',
      generation: '1',
      catchrate: 17.5,
    },
    {
      name: 'Hypno',
      Number: 97,
      type: 'Psychic',
      generation: '1',
      catchrate: 17.5,
    },
    {
      name: 'Krabby',
      Number: 98,
      type: 'Water',
      generation: '1',
      catchrate: 17.5,
    },
    {
      name: 'Kingler',
      Number: 99,
      type: 'Water',
      generation: '1',
      catchrate: 17.5,
    }
    {
      name: 'Voltorb',
      Number: 100,
      type: 'Electric',
      generation: '1',
},
{
      name: 'Electrode',
      Number: 101,
      type: 'Electric',
      generation: '1',
},
{
      name: 'Exeggecute',
      Number: 102,
      type: 'Grass', 'Psychic',
      generation: '1',
},
{
      name: 'Exeggutor',
      Number: 103,
      type: 'Grass', 'Psychic',
      generation: '1',
},
{
      name: 'Cubone',
      Number: 104,
      type: 'Ground',
      generation: '1',
},
{
      name: 'Marowak',
      Number: 105,
      type: 'Ground',
      generation: '1',
},
{
     name: 'Hitmonlee',
      Number: 106,
      type: 'fighting',
      generation: '1',
},
{
     name: 'Hitmonchan',
      Number: 107,
      type: 'Fighting',
      generation: '1',
},
{
      name: 'Lickitung',
      Number: 108,
      type: 'Normal',
      generation: '1',
},
{
      name: 'Koffing',
      Number: 109,
      type: 'Poison',
      generation: '1',
},
{
      name: 'Weezing',
      Number: 110,
      type: 'Poison',
      generation: '1',
},
{
    name: 'Rhyhorn',
      Number: 111,
      type: 'Ground', 'Rock'
      generation: '1',
},
{
    name: 'Rhydon',
      Number: 112,
      type: 'Ground','Rock'
      generation: '1',
},
{
    name: 'Chansey',
      Number: 113,
      type: 'Normal',
      generation: '1',
},
{
    name: 'Tangela',
      Number: 114,
      type: 'Grass',
      generation: '1',
},
{
    name: 'Kangaskahn',
      Number: 115,
      type: 'Normal',
      generation: '1',
},
{
    name: 'Horsea',
      Number: 116,
      type: 'Water',
      generation: '1',
},
{
    name: 'Seadra',
      Number: 117,
      type: 'Water',
      generation: '1',
},
{
    name: 'Goldeen',
      Number: 118,
      type: 'Water',
      generation: '1',
},
{
    name: 'Seaking',
      Number: 119,
      type: 'Water',
      generation: '1',
},
{
    name: 'Staryu',
      Number: 120,
      type: 'Water',
      generation: '1',
},
{
    name: 'Starmie',
      Number: 121,
      type: 'Water', 'Psychic',
      generation: '1',
},
{
    name: 'Mr. Mime',
      Number: 122,
      type: 'Psychic', 'Fairie',
      generation: '1',
},
{
    name: 'Scyther',
      Number: 123,
      type: 'Bug', 'Flying',
      generation: '1',
},
{
    name: 'Jynx',
      Number: 124,
      type: 'Ice', 'Psychic',
      generation: '1',
},
{
    name: 'Electabuzz',
      Number: 125,
      type: 'Electric',
      generation: '1',
},
{
    name: 'Magmar',
      Number: 126,
      type: 'Fire',
      generation: '1',
},

{
    name: 'Pinsir',
      Number: 127,
      type: 'Bug',
      generation: '1',
},
{
    name: 'Tauros',
      Number: 128,
      type: 'Normal',
      generation: '1',
},
{
    name: 'Magikarp',
      Number: 129,
      type: 'Water',
      generation: '1',
},
{
    name: 'Gyarados',
      Number: 130,
      type: 'Water', 'Flying',
      generation: '1',
},
{
    name: 'Lapras',
      Number: 131,
      type: 'Water', 'Ice',
      generation: '1',
},
{
    name: 'Ditto',
      Number: 132,
      type: 'Normal',
      generation: '1',
},
{
    name: 'Eevee',
      Number: 133,
      type: 'Normal',
      generation: '1',
},
{
    name: 'Vaporeon',
      Number: 134,
      type: 'Water',
      generation: '1',
},
{
    name: 'Jolteon',
      Number: 135,
      type: 'Electric',
      generation: '1',
},
{
    name: 'Flareon',
      Number: 136,
      type: 'Fire',
      generation: '1',
},
{
    name: 'Porygon',
      Number: 137,
      type: 'Normal',
      generation: '1',
},
{
    name: 'Omanyte',
      Number: 138,
      type: 'Water', 'Rock',
      generation: '1',
},
{
    name: 'Omastar',
      Number: 139,
      type: 'Water', 'Rock',
      generation: '1',
},
{
    name: 'Kabuto',
      Number: 140,
      type: 'Water', 'Rock',
      generation: '1',
},
{
    name: 'Kabutops',
      Number: 141,
      type: 'Water', 'Rock',
      generation: '1',
},
{
    name: 'Aerodactyl',
      Number: 142,
      type: 'Rock', 'Flying',
      generation: '1',
},
{
    name: 'Snorlax',
      Number: 143,
      type: 'Normal',
      generation: '1',
},
{
    name: 'Articuno',
      Number: 144,
      type: 'Ice', 'Flying',
      generation: '1',
},
{
    name: 'Zapdos',
      Number: 145,
      type: 'Electric', 'Flying',
      generation: '1',
},
{
    name: 'Moltres',
      Number: 146,
      type: 'Fire', 'Flying',
      generation: '1',
},
{
    name: 'Dratini',
      Number: 147,
      type: 'Dragon',
      generation: '1',
},
{
    name: 'Dragonair',
      Number: 148,
      type: 'Dragon',
      generation: '1',
},
{
    name: 'Dragonite',
      Number: 149,
      type: 'Dragon', 'Flying',
      generation: '1',
},
{
    name: 'Mewtwo',
      Number: 150,
      type: 'Psychic',
      generation: '1',
},
{
    name: 'Mew',
      Number: 151,
      type: 'Psychic',
      generation: '1',
}]

    const seedCharacters = () => Character.bulkCreate(characterData)
    module.exports = seedCharacters;
