const {Character} = require('../models');

const characterdata = [
    {
      name: 'Bulbasaur',
      number: 1,
      type: 'Grass, Poison',
      generation: '1',
      catchrate: 11.9,
    },
    {
      name: 'Ivysaur',
      number: 2,
      type: 'Grass, Poison',
      generation: '1',
      catchrate: 11.9,
    },
    {
      name: 'Venusaur',
      number: 3,
      type: 'Grass, Poison',
      generation: '1',
      catchrate: 11.9,
    },
    {
      name: 'Charmander ',
      number: 4,
      type: 'Fire',
      generation: '1',
      catchrate: 11.9,
    },
    {
      name: 'Charmeleon',
      number: 5,
      type: 'Fire',
      generation: '1',
      catchrate: 11.9,
    },
    {
      name: 'Charizard',
      number: 6,
      type: 'Fire',
      generation: '1',
      catchrate: 11.9,
    },
    {
      name: 'Squirtle ',
      number: 7,
      type: 'Water',
      generation: '1',
      catchrate: 11.9,
    },
    {
      name: 'Wartortle',
      number: 8,
      type: 'Water',
      generation: '1',
      catchrate: 11.9,
    },
    {
      name: 'Blastoise',
      number: 9,
      type: 'Water',
      generation: '1',
      catchrate: 11.9,
    },
    {
      name: 'Caterpie',
      number: 10,
      type: 'Bug',
      generation: '1',
      catchrate: 43.9,
    },
    {
      name: 'Metapod',
      number: 11,
      type: 'Bug',
      generation: '1',
      catchrate: 24.9,
    },
    {
      name: 'Butterfree',
      number: 12,
      type: 'Bug, Flying',
      generation: '1',
      catchrate: 11.9,
    },
    {
      name: 'Weedle',
      number: 13,
      type: 'Bug, Poison',
      generation: '1',
      catchrate: 43.9,
    },
    {
      name: 'Kakuna',
      number: 14,
      type: 'Bug, Poison',
      generation: '1',
      catchrate: 24.9,
    },
    {
      name: 'Beedrill',
      number: 15,
      type: 'Bug, Poison',
      generation: '1',
      catchrate: 11.9,
    },
    {
      name: 'Pidgey',
      number: 16,
      type: 'Normal, Flying',
      generation: '1',
      catchrate: 43.9,
    },
    {
      name: 'Pidgey',
      number: 17,
      type: 'Normal, Flying',
      generation: '1',
      catchrate: 24.9,
    },
    {
      name: 'Pidgeot',
      number: 18,
      type: 'Normal, Flying',
      generation: '1',
      catchrate: 11.9,
    },
    {
      name: 'Rattata',
      number: 19,
      type: 'Normal',
      generation: '1',
      catchrate: 43.9,
    },
    {
      name: 'Raticate',
      number: 20,
      type: 'Normal',
      generation: '1',
      catchrate: 26,
    },
    {
      name: 'Spearow',
      number: 21,
      type: 'Normal, Flying',
      generation: '1',
      catchrate: 43.9,
    },
    {
      name: 'Fearow',
      number: 22,
      type: 'Normal, Flying',
      generation: '1',
      catchrate: 20.1,
    },
    {
      name: 'Ekans',
      number: 23,
      type: 'Poison',
      generation: '1',
      catchrate: 43.9,
    },
    {
      name: 'Arbok',
      number: 24,
      type: 'Poison',
      generation: '1',
      catchrate: 20.1,
    },
    {
      name: 'Pikachu',
      number: 25,
      type: 'Electric',
      generation: '1',
      catchrate: 35.2,
    },
    {
      name: 'Raichu',
      number: 26,
      type: 'Electric',
      generation: '1',
      catchrate: 17.5,
    },
    {
      name: 'Sandshrew',
      number: 27,
      type: 'Ground',
      generation: '1',
      catchrate: 17.5,
    },
    {
      name: 'Sandslash',
      number: 28,
      type: 'Ground',
      generation: '1',
      catchrate: 17.5,
    },
    {
      name: 'NidoranMale',
      number: 29,
      type: 'Poison',
      generation: '1',
      catchrate: 17.5,
    },
    {
      name: 'Nidorina',
      number: 30,
      type: 'Poison',
      generation: '1',
      catchrate: 17.5,
    },
    {
      name: 'Nidoqueen',
      number: 31,
      type: 'Poison, Ground',
      generation: '1',
      catchrate: 17.5,
    },
    {
      name: 'NidoranFemale',
      number: 32,
      type: 'Poison',
      generation: '1',
      catchrate: 17.5,
    },
    {
      name: 'Nidorino',
      number: 33,
      type: 'Poison',
      generation: '1',
      catchrate: 17.5,
    },
    {
      name: 'Nidoking',
      number: 34,
      type: 'Poison, Ground',
      generation: '1',
      catchrate: 17.5,
    },
    {
      name: 'Clefairy',
      number: 35,
      type: 'Fairy',
      generation: '1',
      catchrate: 17.5,
    },
    {
      name: 'Clefable',
      number: 36,
      type: 'Fairy',
      generation: '1',
      catchrate: 17.5,
    }, 
    {
      name: 'Vulprix',
      number: 37,
      type: 'Fire',
      generation: '1',
      catchrate: 17.5,
    }, 
     {
      name: 'Ninetables',
      number: 38,
      type: 'Fire',
      generation: '1',
      catchrate: 17.5,
    },  
    {
      name: 'Jigglypuff',
      number: 39,
      type: 'Normal, Fairy',
      generation: '1',
      catchrate: 17.5,
    },  
    {
      name: 'Wigglytuff',
      number: 40,
      type: 'Normal, Fairy',
      generation: '1',
      catchrate: 17.5,
    }, 
    {
      name: 'Zubat',
      number: 41,
      type: 'Poison, Flying',
      generation: '1',
      catchrate: 17.5,
    },  
    {
      name: 'Golbat',
      number: 42,
      type: 'Poison, Flying',
      generation: '1',
      catchrate: 17.5,
    },  
    {
      name: 'Oddish',
      number: 43,
      type: 'Grass, Poison',
      generation: '1',
      catchrate: 17.5,
    },  
    {
      name: 'Gloom',
      number: 44,
      type: 'Grass, Poison',
      generation: '1',
      catchrate: 17.5,
    },  
    {
      name: 'Vileplume',
      number: 45,
      type: 'Grass, Poison',
      generation: '1',
      catchrate: 17.5,
    }, 
    {
      name: 'Paras',
      number: 46,
      type: 'Bug, Grass',
      generation: '1',
      catchrate: 17.5,
    }]

    const seedCharacters=()=> Character.bulkCreate(characterdata)
    module.exports = seedCharacters